insert into part values (1, '25x200 mm. trykimp. brædt', 'Træ', null, null, 'stk', 'Understernbrædder til for & bag ende');
insert into part values (2, '25x200 mm. trykimp. brædt', 'Træ', null, null, 'stk', 'Understernbrædder til siderne');
insert into part values (3, '25x125 mm. trykimp. brædt', 'Træ', null, null, 'stk', 'Oversternbrædder til forenden');
insert into part values (4, '25x125 mm. trykimp. brædt', 'Træ', null, null, 'stk', 'Oversternbrædder til siderne');
insert into part values (5, '38x75 mm. Lægte ubh.', 'Træ', null, null, 'stk', 'Til z på bagside af dør');
insert into part values (6, '45x95 mm. Reglar ub.', 'Træ', null, null, 'stk', 'Løsholter til skur gavle');
insert into part values (7, '45x95 mm. Reglar ub.', 'Træ', null, null, 'stk', 'Løsholter til skur sider');
insert into part values (8, '45x195 mm. Spærtræ ubh.', 'Træ', null, null, 'stk', 'Remme i sider sadles ned i stolper');
insert into part values (9, '45x195 mm. Spærtræ ubh.', 'Træ', null, null, 'stk', 'Remme i sider sadles ned i stolper (skur del, deles)');
insert into part values (10, '45x195 mm. Spærtræ ubh.', 'Træ', null, null, 'stk', 'Spær monteres på rem');
insert into part values (11, '97x97 mm. Trykimp. Stolpe', 'Træ', null, null, 'stk', 'Stolper nedgraves 90cm i jord');
insert into part values (12, '19x100 mm. Trykimp. Bræt', 'Træ', null, null, 'stk', 'til beklædning af skur 1 på 2');
insert into part values (13, '19x100 mm. Trykimp. Bræt', 'Træ', null, null, 'stk', 'Vandbræt på stern i sider');
insert into part values (14, '19x100 mm. Trykimp. Bræt', 'Træ', null, null, 'stk', 'Vandbræt på stern i forende');
insert into part values (15, 'Plasmo Ecolite blåtonet', 'Tag', 600, null, 'stk', 'Tagplader monteres på spær');
insert into part values (16, 'Plasmo Ecolite blåtonet', 'Tag', 360, null, 'stk', 'Tagplader monteres på spær');
insert into part values (17, 'Plastmo bundskruer 200 stk', 'Løsdele', null, null, 'pakke', 'Skruer til tagplader');
insert into part values (18, 'Hulbånd 1x20mm. 10 mtr', 'Løsdele', null, null, 'rulle', 'Til vindkryds på spær');
insert into part values (19, 'Universal 190mm. højre', 'Løsdele', null, null, 'stk', 'Til montering af spær på rem');
insert into part values (20, 'Universal 190mm. venstre', 'Løsdele', null, null, 'stk', 'Til montering af spær på rem');
insert into part values (21, '4,5 x 60mm. skruer 200 stk.', 'Løsdele', null, null, 'pakke', 'Til montering af stern og vandbræt');
insert into part values (22, '4,0 x 50mm. beslagskruer 250 stk.', 'Løsdele', null, null, 'pakke', 'Til montering af universalbeslag + hulbånd');
insert into part values (23, 'Breddebolt 10 x 120 mm.', 'Løsdele', null, null, 'stk', 'Til montering af rem på stolper');
insert into part values (24, 'Firkantskriver 40x40x11 mm.', 'Løsdele', null, null, 'stk', 'Til montering af rem på stolper');
insert into part values (25, '4,5 x 70mm. skruer 400 stk.', 'Løsdele', null, null, 'pakke', 'Til montering af yderste beklædning');
insert into part values (26, '4,5 x 50mm. skruer 300 stk.', 'Løsdele', null, null, 'pakke', 'Til montering af inderste beklædning');
insert into part values (27, 'Stalddørsgreb 50x75', 'Løsdele', null, null, 'sæt', 'Til lås på dør i skur');
insert into part values (28, 'T-hængsel 390 mm.', 'Løsdele', null, null, 'stk', 'Til skurdør');
insert into part values (29, 'Vinkelbeslag 35', 'Løsdele', null, null, 'stk', 'Til monetring af løsholter i skur');

