insert into Part values (1001, '25x200 mm. trykimp. brædt', 'Træ', null, null, 'stk', 'Understernbrædder til for & bag ende');
insert into Part values (1002, '25x200 mm. trykimp. brædt', 'Træ', null, null, 'stk', 'Understernbrædder til siderne');
insert into Part values (1003, '25x125 mm. trykimp. brædt', 'Træ', null, null, 'stk', 'Oversternbrædder til forenden');
insert into Part values (1004, '25x125 mm. trykimp. brædt', 'Træ', null, null, 'stk', 'Oversternbrædder til siderne');
insert into Part values (1005, '38x75 mm. Lægte ubh.', 'Træ', null, null, 'stk', 'Til z på bagside af dør');
insert into Part values (1006, '45x95 mm. Reglar ub.', 'Træ', null, null, 'stk', 'Løsholter til skur gavle');
insert into Part values (1007, '45x95 mm. Reglar ub.', 'Træ', null, null, 'stk', 'Løsholter til skur sider');
insert into Part values (1008, '45x195 mm. Spærtræ ubh.', 'Træ', null, null, 'stk', 'Remme i sider sadles ned i stolper');
insert into Part values (1009, '45x195 mm. Spærtræ ubh.', 'Træ', null, null, 'stk', 'Remme i sider sadles ned i stolper (skur del, deles)');
insert into Part values (1010, '45x195 mm. Spærtræ ubh.', 'Træ', null, null, 'stk', 'Spær monteres på rem');
insert into Part values (1011, '97x97 mm. Trykimp. Stolpe', 'Træ', null, null, 'stk', 'Stolper nedgraves 90cm i jord');
insert into Part values (1012, '19x100 mm. Trykimp. Bræt', 'Træ', null, null, 'stk', 'til beklædning af skur 1 på 2');
insert into Part values (1013, '19x100 mm. Trykimp. Bræt', 'Træ', null, null, 'stk', 'Vandbræt på stern i sider');
insert into Part values (1014, '19x100 mm. Trykimp. Bræt', 'Træ', null, null, 'stk', 'Vandbræt på stern i forende');
insert into Part values (2001, 'Plasmo Ecolite blåtonet', 'Tag', 600, null, 'stk', 'Tagplader monteres på spær');
insert into Part values (2002, 'Plasmo Ecolite blåtonet', 'Tag', 360, null, 'stk', 'Tagplader monteres på spær');
insert into Part values (3001, 'Plastmo bundskruer 200 stk', 'Løsdele', null, null, 'pakke', 'Skruer til tagplader');
insert into Part values (3002, 'Hulbånd 1x20mm. 10 mtr', 'Løsdele', null, null, 'rulle', 'Til vindkryds på spær');
insert into Part values (3003, 'Universal 190mm. højre', 'Løsdele', null, null, 'stk', 'Til montering af spær på rem');
insert into Part values (3004, 'Universal 190mm. venstre', 'Løsdele', null, null, 'stk', 'Til montering af spær på rem');
insert into Part values (3005, '4,5 x 60mm. skruer 200 stk.', 'Løsdele', null, null, 'pakke', 'Til montering af stern og vandbræt');
insert into Part values (3006, '4,0 x 50mm. beslagskruer 250 stk.', 'Løsdele', null, null, 'pakke', 'Til montering af universalbeslag + hulbånd');
insert into Part values (3007, 'Breddebolt 10 x 120 mm.', 'Løsdele', null, null, 'stk', 'Til montering af rem på stolper');
insert into Part values (3008, 'Firkantskriver 40x40x11 mm.', 'Løsdele', null, null, 'stk', 'Til montering af rem på stolper');
insert into Part values (3009, '4,5 x 70mm. skruer 400 stk.', 'Løsdele', null, null, 'pakke', 'Til montering af yderste beklædning');
insert into Part values (3010, '4,5 x 50mm. skruer 300 stk.', 'Løsdele', null, null, 'pakke', 'Til montering af inderste beklædning');
insert into Part values (3011, 'Stalddørsgreb 50x75', 'Løsdele', null, null, 'sæt', 'Til lås på dør i skur');
insert into Part values (3012, 'T-hængsel 390 mm.', 'Løsdele', null, null, 'stk', 'Til skurdør');
insert into Part values (3013, 'Vinkelbeslag 35', 'Løsdele', null, null, 'stk', 'Til monetring af løsholter i skur');

insert into Customer values (0001, 'user@test.dk', 'User1', 696969, '123' );
insert into FogUser values (001, 'test@test.dk', 'Fog1', '123' );